name: "OwnTone Server"
version: "1.0.0"
description: "Server multimediale DAAP (iTunes), AirPlay e Chromecast per la tua musica"
slug: "owntone_server"
url: "https://github.com/Dino0005/homeassistant-nextfiles/tree/main/owntone-server"
arch:
  - amd64
  - aarch64
init: false
startup: services
boot: auto
host_network: true
audio: true
cap_add:
  - NET_BIND_SERVICE
map:
  - media:ro
options:
  log_level: "info"
schema:
  log_level: "list(trace|debug|info|warn|error)"
