build_from:
  # Using SHA blocked to avoid issues with 3.23 latest
  # Tested and working aarch64-base version from: ghcr.io/home-assistant/aarch64-base:3.23-2026.04.0
  aarch64: ghcr.io/home-assistant/aarch64-base@sha256:4d75aa586e570c635e226dd1ac55277f4acf30544dcb06cff99ee4ac79212a62
  # amd64-base version from: ghcr.io/home-assistant/amd64-base:3.23-2026.04.0
  amd64: ghcr.io/home-assistant/amd64-base@sha256:7c2e95909a2b767bd23a594c35240caf3a954e93a3408675388ba8ca0b20cbb3
labels:
  org.opencontainers.image.title: "Nextfiles"
  org.opencontainers.image.description: "Self-hosted file storage solution with MariaDB database, APCu cache, Redis support for Home Assistant"
  org.opencontainers.image.source: "https://github.com/Dino0005/homeassistant-nextfiles"
  org.opencontainers.image.licenses: "MIT"
args:
  NEXTCLOUD_VERSION: "33.0.2"
  PHP_VERSION: "84"
