build_from:
  # Using SHA blocked to avoid issues with 3.23 latest
  # Tested and working aarch64-base version from: ghcr.io/home-assistant/aarch64-base:3.23-2026.05.0
  aarch64: ghcr.io/home-assistant/aarch64-base@sha256:98fae7002645c9a4a3b490686750cce0b97801be64e39b29ca8676d7c8dd2bd4
  # amd64-base version from: ghcr.io/home-assistant/amd64-base:3.23-2026.05.0
  amd64: ghcr.io/home-assistant/amd64-base@sha256:b2edae5a74fa198b423e94f654ce0b03d667488e23ffec7dd6a4f5976f2af85c
labels:
  org.opencontainers.image.title: "Nextfiles"
  org.opencontainers.image.description: "Self-hosted file storage solution with MariaDB database, APCu cache, Redis support for Home Assistant"
  org.opencontainers.image.source: "https://github.com/Dino0005/homeassistant-nextfiles"
  org.opencontainers.image.licenses: "MIT"
args:
  NEXTCLOUD_VERSION: "33.0.3"
  PHP_VERSION: "84"
