build_from:
  # Using SHA blocked to avoid issues with 3.24 latest
  # Tested and working aarch64-base version from: ghcr.io/home-assistant/aarch64-base:3.24-2026.06.1
  aarch64: ghcr.io/home-assistant/aarch64-base@sha256:2ac8f73090063ac23e63a1adc144bd1d8aa88f5e5d92c68898102e81046084a4
  # amd64-base version from: ghcr.io/home-assistant/amd64-base:3.24-2026.06.1
  amd64: ghcr.io/home-assistant/amd64-base@sha256:2b60b12b34ccd960fda082d223b40dbb2b0bb40af95f12912233b736f27fc47a
labels:
  org.opencontainers.image.title: "Nextfiles"
  org.opencontainers.image.description: "Self-hosted file storage solution with MariaDB database, APCu cache, Redis support for Home Assistant"
  org.opencontainers.image.source: "https://github.com/Dino0005/homeassistant-nextfiles"
  org.opencontainers.image.licenses: "MIT"
args:
  NEXTCLOUD_VERSION: "33.0.6"
  PHP_VERSION: "85"
