name: Nextfiles
version: "1.1.4"
slug: nextfiles
description: Self-hosted file storage solution with MariaDB database, APCu cache and Redis support for Home Assistant
url: https://github.com/Dino0005/homeassistant-nextfiles
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
boot: auto
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
map:
  - share:rw
options:
  admin_user: admin
  admin_password: null
  mariadb_host: core-mariadb
  mariadb_database: nextcloud
  mariadb_username: nextcloud
  mariadb_password: null
  trusted_domains:
    - localhost
  trusted_proxies:
    - 172.30.33.0/24
  max_upload_size: 512M
  memory_limit: 512M
  redis_host: ""
  redis_port: 6379
  redis_password: ""
  default_phone_region: IT
schema:
  admin_user: str
  admin_password: password
  mariadb_host: str
  mariadb_database: str
  mariadb_username: str
  mariadb_password: password
  trusted_domains:
    - str
  trusted_proxies:
    - str
  max_upload_size: str
  memory_limit: str
  redis_host: str?
  redis_port: port?
  redis_password: password?
  default_phone_region: str
#image: ghcr.io/dino0005/nextfiles-{arch}
